# Generated by Django 4.1.5 on 2023-01-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('network', models.CharField(max_length=50)),
                ('episodes', models.IntegerField()),
                ('cast', models.JSONField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
