# Generated by Django 4.1.5 on 2023-01-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='cast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
